'use client';

import { useEffect, useState } from 'react';
import api from '@/services/api/axios';
import { useAuthStore } from '@/store/auth/useAuthStore';
import { toast } from '@/lib/toast';
import { formatApiError } from '@/lib/formatApiError';

type ActivityLog = {
  id: string;
  user_name: string;
  action: string;
  entity_type: string;
  entity_id?: string | null;
  description: string;
  extra_data?: Record<string, unknown> | null;
  ip_address?: string | null;
  created_at: string;
};

export default function ActivityLogFeed() {
  const { user } = useAuthStore();
  const [logs, setLogs] = useState<ActivityLog[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadActivity = async () => {
      if (!user) return;
      try {
        const isAdmin = ['ADMIN', 'MANAGER'].includes(user.role);
        const endpoint = isAdmin ? '/activity-logs' : '/activity-logs/my-activity';
        const response = await api.get(endpoint, { params: { limit: 50 } });
        setLogs(response.data);
      } catch (err: unknown) {
        toast.error(formatApiError(err, 'Unable to load activity logs'));
        setError(formatApiError(err, 'Unable to load activity logs.'));
      } finally {
        setIsLoading(false);
      }
    };

    loadActivity();
  }, [user]);

  const isAdmin = user && ['ADMIN', 'MANAGER'].includes(user.role);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-gray-900">{isAdmin ? 'System-wide Activity' : 'My Activity'}</h2>
        <p className="text-sm text-gray-500">
          {isAdmin ? 'Audit trail of all actions performed in the system.' : 'Track the activity events generated by your account.'}
        </p>
      </div>

      {isLoading ? (
        <div className="rounded-xl border border-gray-200 bg-white p-6 text-sm text-gray-500">Loading activity...</div>
      ) : error ? (
        <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error}</div>
      ) : logs.length === 0 ? (
        <div className="rounded-xl border border-gray-200 bg-white p-6 text-sm text-gray-500">No activity found.</div>
      ) : (
        <div className="space-y-4">
          {logs.map((log) => (
            <div key={log.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div>
                  <div className="flex items-center space-x-2">
                    <p className="text-sm font-semibold text-slate-900">{log.action}</p>
                    <span className="text-xs text-slate-400">by {log.user_name}</span>
                  </div>
                  <p className="mt-2 text-sm text-slate-600">{log.description}</p>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500">
                    <span>{log.entity_type}</span>
                    {log.entity_id ? <span>Entity: {log.entity_id}</span> : null}
                    {log.ip_address ? <span>IP: {log.ip_address}</span> : null}
                  </div>
                </div>
                <div className="text-right text-xs text-slate-400">
                  <p>{new Date(log.created_at).toLocaleString()}</p>
                </div>
              </div>
              {log.extra_data ? (
                <pre className="mt-4 overflow-x-auto rounded-lg bg-slate-50 p-3 text-xs text-slate-600">{JSON.stringify(log.extra_data, null, 2)}</pre>
              ) : null}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
